### ISSUE TITLE
Missing Key:Value pairs.

### ISSUE THREAD

**Issue by mathew-addepar** [JupiterOne/graph-bamboohr#11]
Looks like there is some missing data being pulled by the api that is available in the Raw Data object. Does this project accept PRs?

**Comment by faf0-addepar** [comment]
Field can probably be added here: https://github.com/JupiterOne/graph-bamboohr/blob/5f9f624012d1f0d07d010056d2778d22b8662548/src/steps/access.ts#L42-L52
